services:
  django:
    build:
      context: ./mysite
      args:
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
        DEBUG: ${DEBUG}
    volumes:
      - ./mysite:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - DEVELOPMENT=True
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb_dev
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env.dev

volumes:
  pgdbdata:
