services:
  django:
    build:
      context: ./mysite
      dockerfile: Dockerfile.prod
      args:
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
    volumes:
      - ./mysite:/usr/src/app
      - static_volume:/home/app/django/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/django/staticfiles
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  pgdbdata:
  static_volume:
