# Generated by Django 5.0.4 on 2024-05-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_languages_language_rename_wordslist_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='complexity',
            new_name='rank',
        ),
    ]
