# Generated by Django 5.0.6 on 2024-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_word_meaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='d',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='doc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='freq',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='lemma',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='pos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='r',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
