# Generated by Django 5.0.6 on 2024-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_word_meaning_remove_word_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(max_length=10),
        ),
    ]
