# Generated by Django 5.0.6 on 2024-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_known_words', models.IntegerField(default=105000)),
                ('rate_change_coefficient', models.FloatField(default=0.25)),
                ('average_theta', models.FloatField(default=-1.5)),
            ],
        ),
    ]
