# Generated by Django 5.0.6 on 2024-05-23 20:52

import django.db.models.deletion
from django.db import migrations, models


def create_default_assessment_parameters(apps, schema_editor):
    AssessmentParameters = apps.get_model("polls", "AssessmentParameters")
    SiteSettings = apps.get_model("polls", "SiteSettings")

    params, created = AssessmentParameters.objects.get_or_create(
        preset_name="default",
        defaults={
            "max_known_words": 105000,
            "rate_change_coefficient": 0.25,
            "average_theta": -1.5,
        },
    )

    SiteSettings.objects.get_or_create(active_assessment_parameters=params)


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_assessmentparameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentparameters",
            name="preset_name",
            field=models.CharField(default="default", max_length=255),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="assessment_parameters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="polls.assessmentparameters",
            ),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_assessment_parameters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.assessmentparameters",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_default_assessment_parameters),
    ]
