# Generated by Django 5.0.6 on 2024-05-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_assessmentparameters_user_session_squashed_0016_rename_name_assessmentparameters_preset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='assessment_parameters',
        ),
    ]
