# Generated by Django 5.0.6 on 2024-05-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_userresponse_assessment_parameters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
